version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  api-gateway:
    build: ./services/api_gateway
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - CATALOG_SERVICE_URL=http://catalog-service:8002
      - ORDERS_SERVICE_URL=http://order-service:8003
      - PAYMENT_SERVICE_URL=http://payment-service:8004
      - RECOMMENDATION_SERVICE_URL=http://recommendation-service:8005

  auth-service:
    build: ./services/auth_service
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./db_data:/app/data
    environment:
      - DB_PATH=/app/data/users.db
      - JWT_SECRET_KEY=chave_super_secreta_do_projeto_com_tamanho_seguro_32+

  catalog-service:
    build: ./services/catalog_service
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    volumes:
      - ./db_data:/app/data
    environment:
      - DB_PATH=/app/data/catalog.db

  order-service:
    build: ./services/order_service
    ports:
      - "8003:8003"
    command: uvicorn main:app --host 0.0.0.0 --port 8003
    volumes:
      - ./db_data:/app/data
    environment:
      - DB_PATH=/app/data/orders_v2.db
      - CATALOG_SERVICE_URL=http://catalog-service:8002

  payment-service:
    build: ./services/payment_service
    ports:
      - "8004:8004"
    command: uvicorn main:app --host 0.0.0.0 --port 8004

  recommendation-service:
    build: ./services/recommendation_service
    ports:
      - "8005:8005"
    command: uvicorn main:app --host 0.0.0.0 --port 8005
